name: 📺Game CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**.yml"
      - "client/**"
      - "server/action-server3/torikime/**"
      - "server/action-server3/rpc/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/**.yml"
      - "client/**"
      - "server/action-server3/torikime/**"
      - "server/action-server3/rpc/**"

jobs:
  build:
    name: ✨Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10.2"
          architecture: "x64"

      # Cache
      - uses: actions/cache@v2
        with:
          path: client/potato/Library
          key: Library-${{ hashFiles('client/potato/Assets/**', 'client/potato/Packages/**', 'client/potato/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: apt update
        run: sudo apt-get update
      - name: Various installations
        run: sudo apt-get install -yq tree
      - name: protocol buffers
        run: sudo apt-get install -yq protobuf-compiler

      - name: ⚗Generate RPC
        run: |
          pushd server/action-server3
          pushd torikime
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
          pipenv install
          pipenv install pyyaml jinja2 inflection
          pipenv run python torikime.py -v -o "../proto" -s "../../../client/potato/Assets/Scripts/Rpc/Generated" -i "../rpc"
          popd
          ./generate_csharp_proto.sh
          # find ./proto -name "*.proto"
          # protoc --proto_path=./proto --csharp_out=../../client/potato/Assets/Scripts/Proto ./proto/*.proto
          popd

      - name: list output
        run: |
          tree server
          tree client/potato/Assets/Scripts

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: client/potato
          allowDirtyBuild: true

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: client/potato
          allowDirtyBuild: true

      # # Output
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: Build
      #     path: client/potato/build
